services:
  stats-server:
    build: ./stats
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5440:5432"
    volumes:
      - stats_pgdata:/var/lib/postgresql/data

  ewm-service:
    build: ./ewm-service
    depends_on:
      - ewm-db
      - stats-server
    environment:
      STATS_BASE_URL: http://stats-server:9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5441:5432"
    volumes:
      - ewm-pgdata:/var/lib/postgresql/data

volumes:
  stats_pgdata:
  ewm-pgdata:
